name = "glamlox"
version = "0.0.1"

description = "Gleam implementation for the Lox language"
licences = ["MIT"]
repository = { type = "github", user = "nach-o-man", repo = "glamlox" }
links = [{ title = "Crafting Interpreters Book", href = "https://craftinginterpreters.com/" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
